// Writes js/m3-baseline.js: the colour scheme of the default look (Baseline seed, Tonal), so a first visit
// paints Material 3 colours without loading the colour library (200 KB). Run after changing the scheme code
// in js/design.js (blocks, ROLES, CUSTOM) or the library:  node tools/m3/baseline.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const src = fs.readFileSync(path.join(root, 'js/design.js'), 'utf8');
const pick = (re) => { const m = src.match(re); if (!m) throw new Error(`not found in design.js: ${re}`); return m[0]; };
const code = [
    pick(/^const ROLES = \[[^]*?\];$/m),
    pick(/^const kebab = .*;$/m),
    pick(/^const CUSTOM = .*;$/m),
    pick(/^const BASELINE = .*;$/m),
    pick(/^function blocks\([^]*?^}$/m),
].join('\n');
const mcu = await import(pathToFileURL(path.join(root, 'js/vendor/material-color-utilities-0.4.0.js')).href);
const { blocks, BASELINE } = new Function('mcu', `${code}\nreturn { blocks, BASELINE };`)(mcu);
const { light, dark } = blocks(mcu, BASELINE, mcu.SchemeTonalSpot);
const css = `:root[data-design="m3"] { ${light} }
@media (prefers-color-scheme: dark) { :root[data-design="m3"]:not([data-theme="light"]) { ${dark} } }
:root[data-design="m3"][data-theme="dark"] { ${dark} }`;
fs.writeFileSync(path.join(root, 'js/m3-baseline.js'), `// Generated by tools/m3/baseline.mjs — the Baseline/Tonal colour scheme, so a first visit needs no colour library
export const BASELINE_TONAL_CSS = ${JSON.stringify(css)};
`);
console.log('js/m3-baseline.js written,', css.length, 'characters');
