#!/usr/bin/env python3
"""Builds css/m3-icons.css: every <svg data-icon="name"> in the app gets the Material Symbols Rounded
drawing of that name in the M3 design (as a CSS mask, so the markup stays AniRoll's). Active navigation
destinations use the filled variant, as M3 does.
Source: @material-symbols/svg-400 (Apache-2.0), `npm pack @material-symbols/svg-400` and unpack.
Usage: python3 tools/m3/icons.py <path to package/rounded>"""
import glob, re, sys, urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
src = Path(sys.argv[1])
FILLED = {'home', 'video_library', 'cyclone', 'explore', 'group', 'favorite', 'bookmark', 'notifications'}

names = set()
for f in [ROOT / 'index.html', *ROOT.glob('js/**/*.js')]:
    if 'vendor' in f.parts:
        continue
    text = f.read_text()
    names |= set(re.findall(r'data-icon="([a-z_]+)"', text))
    # emptyIcon() / status maps hold the names as strings
    for block in re.findall(r'const (?:EMPTY_M3|STATUS_M3) = \{([^}]*)\}', text):
        names |= set(re.findall(r"'([a-z_]+)'", block))
missing = sorted(n for n in names if not (src / f'{n}.svg').exists())
if missing:
    sys.exit('Not in Material Symbols Rounded: ' + ', '.join(missing))

def uri(path):
    svg = re.sub(r'\s(width|height)="\d+"', '', path.read_text().strip())
    return 'url("data:image/svg+xml,' + urllib.parse.quote(svg, safe=' =:/-"') .replace('"', "'") + '")'

out = ['/* Generated by tools/m3/icons.py from Material Symbols Rounded 400 (@material-symbols/svg-400, Apache-2.0).',
       '   Do not edit by hand. */',
       ':root[data-design="m3"] svg[data-icon] { background-color: currentColor; -webkit-mask: var(--m3i) center / contain no-repeat; mask: var(--m3i) center / contain no-repeat; stroke: none; fill: none; }',
       ':root[data-design="m3"] svg[data-icon] > * { display: none; }']
for n in sorted(names):
    out.append(f':root[data-design="m3"] svg[data-icon="{n}"] {{ --m3i: {uri(src / f"{n}.svg")}; }}')
for n in sorted(names & FILLED):
    fill = src / f'{n}-fill.svg'
    if fill.exists():
        out.append(f':root[data-design="m3"] :is(.active, .liked, [aria-current]) > svg[data-icon="{n}"] {{ --m3i: {uri(fill)}; }}')
(ROOT / 'css' / 'm3-icons.css').write_text('\n'.join(out) + '\n')
print(len(names), 'icons:', ' '.join(sorted(names)))
