#!/usr/bin/env python3
"""Builds css/m3-shapes.css: a few shapes of the M3 Expressive shape library as clip-path polygons
(--m3-shape-<name>), plus the loading indicator's morph keyframes. All polygons use the same number of
points, so the browser can morph between any two of them with a transition.
Usage: python3 tools/m3/shapes.py"""
import math
from pathlib import Path

N = 72
ROOT = Path(__file__).resolve().parents[2]

def radial(fn):
    pts = []
    for i in range(N):
        t = 2 * math.pi * i / N - math.pi / 2
        r = fn(t)
        pts.append(f'{50 + 50 * r * math.cos(t):.2f}% {50 + 50 * r * math.sin(t):.2f}%')
    return 'polygon(' + ','.join(pts) + ')'

def wave(k, a, sharp=1.0):
    def fn(t):
        c = math.cos(k * t)
        c = math.copysign(abs(c) ** sharp, c)
        return (1 - a) + a * c
    return fn

def superellipse(n):
    # squircle: |x|^n + |y|^n = 1
    def fn(t):
        c, s = abs(math.cos(t)), abs(math.sin(t))
        return 1 / ((c ** n + s ** n) ** (1 / n)) * 0.72
    return fn

def arch():
    # full half circle on top, straight sides, rounded bottom corners (M3 "arch")
    pts = []
    per = N // 4
    for i in range(per * 2):               # top half circle, left to right
        a = math.pi + math.pi * i / (per * 2 - 1)
        pts.append((50 + 50 * math.cos(a), 50 + 50 * math.sin(a)))
    for i in range(per):                   # bottom right corner
        a = 0 + (math.pi / 2) * i / (per - 1)
        pts.append((100 - 16 + 16 * math.cos(a), 100 - 16 + 16 * math.sin(a)))
    for i in range(per):                   # bottom left corner
        a = math.pi / 2 + (math.pi / 2) * i / (per - 1)
        pts.append((16 + 16 * math.cos(a), 100 - 16 + 16 * math.sin(a)))
    return 'polygon(' + ','.join(f'{x:.2f}% {y:.2f}%' for x, y in pts) + ')'

SHAPES = {
    'circle': radial(lambda t: 1),
    'cookie9': radial(wave(9, 0.07)),
    'cookie12': radial(wave(12, 0.06)),
    'cookie4': radial(wave(4, 0.13)),
    'clover4': radial(wave(4, 0.24, 0.6)),
    'flower': radial(wave(8, 0.16, 0.7)),
    'sunny': radial(wave(8, 0.1, 2.2)),
    'burst': radial(wave(12, 0.14, 2.6)),
    'squircle': radial(superellipse(4)),
    'arch': arch(),
}

out = ['/* Generated by tools/m3/shapes.py: shapes from the M3 Expressive shape library as clip-paths. */',
       ':root[data-design="m3"] {']
out += [f'    --m3-shape-{k}: {v};' for k, v in SHAPES.items()]
out.append('}')
seq = ['cookie9', 'clover4', 'sunny', 'cookie4', 'flower', 'cookie9']
out.append('@keyframes m3Morph {')
for i, k in enumerate(seq):
    out.append(f'    {i * 100 // (len(seq) - 1)}% {{ clip-path: var(--m3-shape-{k}); }}')
out.append('}')
(ROOT / 'css' / 'm3-shapes.css').write_text('\n'.join(out) + '\n')
print('shapes:', ', '.join(SHAPES))
